import random

### like minecraft splash text xD

def get_not_so_random_quote():
    quotes = [
        "Don't trust, verify!",
        "Freedom is the right to tell people what they do not want to hear.",
        "The more corrupt the state, the more numerous the laws.",
        "Liberty means responsibility. That is why most men dread it.",
        'Who is John Galt?',
        'Liberdade é pouco. O que desejo ainda não tem nome.',
        'All / 21m',
        '>: 4 8 15 16 23 42',
        'Os alquimistas já estão no corredor...',
        'Wake up, Neo',
        "May the Force be with you.",
        "I am your father.",
        "To infinity and beyond!",
        "You can't handle the truth!",
        "Houston, we have a problem.",
        "Just keep swimming.",
        "I see dead people.",
        "There's no place like home.",
        "SAY HELLO TO MY LITTLE FRIEND TRA TRA TRA !!!",
        "Carpe diem. Seize the day, boys.",
        "E.T. phone home.",
        "To boldly go where no man has gone before.",
        "I'm gonna make him an offer he can't refuse.",
        "It's not personal, Sonny. It's strictly business.",
        "Luca Brasi sleeps with the fishes.",
        "Leave the gun. Take the cannoli.",
        "Look how they massacred my boy!",
        "I know it was you, Fredo. You broke my heart. You broke my heart."
        "Minecraft",
        "You are awesome!",
        "Minecraft is the best!",
        "Don't forget to sleep!",
        "This is a splash text!",
        "You are not alone.",
        "Have fun!",
        "Explore the world!",
        "Discover new things!",
        "Try to survive!",
        "Good luck!",
        "Have a nice day!",
        "Enjoy the adventure!",
        "Be creative!",
        "Don't be afraid to build!",
        "Keep calm and mine on!",
        "Dig deep!",
        "Be prepared!",
        "Stay safe!",
        "Craft your way to victory!",
        "Don't forget to eat!",
        "Be brave!",
        "Have a great time!",
        "Adventure awaits!",
        "Build something amazing!",
        "Explore the unknown!",
        "You are a hero!",
        "Survive the night!",
        "Craft your dreams!",
        "Don't give up!",
        "You can do it!",
        "Keep mining!",
        "Find new treasures!",
        "Stay curious!",
        "Have fun exploring!",
        "Be creative!",
        "Build your world!",
        "Craft your own path!",
        "Enjoy the journey!",
        "See you in the game!",
        "Game on!",
        "Build and explore!",
        "Craft your story!",
        "Play and have fun!",
        "Discover new lands!",
        "Stay adventurous!",
        "Happy mining!",
        "Craft your adventure!",
        "Welcome back!",
        "The adventure continues!",
        "Build your legacy!",
        "Explore and conquer!",
        "You are a master builder!",
        "Survival is key!"        
    ]
    return random.choice(quotes)
